# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:QbB30/emnFHTW4RWmJu2+4FVFw==,iv:olc1gHUzyYK+kHienfjpVbPSlKEVspwHKG5s3WoVs+s=,tag:dVFlS1JtlIMelO7QUc7tuA==,type:str]
    api-key: ENC[AES256_GCM,data:KX5bfR7oVTVqcXy6oflAdhw83rU0ZClFAT8L7NRNOHzT00Ow9w==,iv:85JHSnBxPtgmb0taSII/YhO8m46ghf3v2nuTV4O6zY4=,tag:w7UU+kAF2P5O5bGm0Te4Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age129gn3vvzvjpjr3ezn25xfrsau0jecym6htyqv6derdpettrvdezq204t4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNEd3TkxacHNSUXZmQk9N
            aHE3bVBXN29BTmNaK2dBVEZKTi92dDhRZ1JZCk9hS0c5T1JmcnkyVmFKRlZPL29G
            SThRZ1JwWSswbkgxNm5QNmd5N2lrSkEKLS0tIHkwWmpxNTM1YzlyMW9qY05EM2JM
            N2Zib0poZjQzNUFnR3ZHOTBzRWJ2ZmcK3zg74XdDSsyRDUqZ1wnJXq9xDKyavHU8
            oyClioO6Gd9RAcgL5DZ4JqCG0Ivcm76CMnzFHsCOnndGspuNwK0K2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T02:19:14Z"
    mac: ENC[AES256_GCM,data:tbpQ4V1hrlYi8lx1tVSlVvxZmP6HSQtV+RaLFUmVtAP8LPnTI8iA+ThShOF34YSlFUC6AXEG6qkuexU1C1J8gmnnXwlNueZr+1nnFp2YeEIzVeSPZ2iJ7PIxWoJzGHzQtT85MOkJLXmbTTQtTklvKY4VavhHj4HB/+mOtBWHxMo=,iv:ZinakVnoUdlvFwBKFJ/yr3hdbJ3cD4xZgLQPnhtbddE=,tag:7oi/aqGZHUBYU6Qg7K5d1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
