---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.99.201-192.168.99.208
  METALLB_K8S_GATEWAY_ADDR: 192.168.99.201
  METALLB_TRAEFIK_ADDR: 192.168.99.202
