# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wfXQMaXmmBLa0T3nGg==,iv:69wNVLqftZrIEul9TeOrecgsOYR2a+xa7GJIJ0CjWdg=,tag:pmQ5/YmY5eJb+lo97du2LA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MB7iQL+ZirvHvxkZbPdCppzBHA==,iv:Tw9f+Yyd1d/bKJPcCXXoiznGk+rPf9bcd1ihrycMN84=,tag:7TX3I6/963wBZrvkRQIvcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age129gn3vvzvjpjr3ezn25xfrsau0jecym6htyqv6derdpettrvdezq204t4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ1BvMkFFcHVHd0RNVnlK
            TkJXaHRNK3pHMWFFM2JUbXQxVGhlT0lhL0FnCkJwS3ppUzNsUkFWNGRVTHNWK01C
            cVdwdU1aZmhDd0NSanBiRXd0a2lvTGcKLS0tIHdkemZWYjJCdTJzeHFmRUxIQkxV
            ZUtiR1FwcWxsTURLTFUzTTc1N0xERDAKvO8IUpT/TmajpN1Yyo7Nep4frjPBy9vv
            rFBJ24H1qz5l4tC7jn/QkS1gkmgKzV3WF8Hb/aafNKnyCOHr3JZApA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-19T02:19:14Z"
    mac: ENC[AES256_GCM,data:tombNhemW7O649HJUDPfwe3BanB1gYkCFGZTdKaQybipAsyA76EhEoQqgO59AICRK1KrPUmEivsHFL/sTi+gLgXjFZFvKCszAO9+DO5sQzhYHW4550hMkE4rxn4bLmp1QfpjI59/9PvhPAj/MT1InZsQYegIC6PA1viBinrw5lU=,iv:MCxtrTD9GtnCGibGg9kiTdfocVxKTWhQrpPXJNDAkXY=,tag:qBhXnSkxlPqpXDQERXbkqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
